# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install pytest-cov
        pip install codecov
        pipenv sync --dev
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
      continue-on-error: true
    - name: Test with pytest
      run: |
        pipenv run pytest --cov = libpythonpro
    - name: Relatório Codecov
      run: |
        codecov
      env:
        token: fc14cea8-b37a-4bcf-a3e7-3c887d331060
